services:
    zookeeper:
        image: "bitnami/zookeeper:latest"
        ports:
            - "2181:2181"
        environment:
            - ALLOW_ANONYMOUS_LOGIN=yes
        networks:
            - kafka-network

    kafka:
        image: "bitnami/kafka:latest"
        ports:
            - "9092:9092"
        environment:
            - KAFKA_BROKER_ID=1
            - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
            - KAFKA_ADVERTISED_LISTENERS=INTERNAL://kafka:29092,EXTERNAL://localhost:9092
            - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
            - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
        networks:
            - kafka-network
        depends_on:
            - zookeeper

    postgres:
        image: postgres:15
        env_file:
            - .env
        ports:
            - "5432:5432"
        networks:
            - kafka-network

    debezium:
        image: debezium/connect:2.7
        platform: linux/arm64
        ports:
            - "8083:8083"
        environment:
            - BOOTSTRAP_SERVERS=kafka:29092
            - GROUP_ID=1
            - CONFIG_STORAGE_TOPIC=my_connect_configs
            - OFFSET_STORAGE_TOPIC=my_connect_offsets
            - STATUS_STORAGE_TOPIC=my_connect_statuses
        depends_on:
            - kafka
            - zookeeper
            - postgres
        networks:
            - kafka-network

networks:
    kafka-network:
        driver: bridge

volumes:
    postgres-data:
        driver: local
